# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase', '>= 2.5.1'
@import Firebase;
target 'CloudCar App' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase’
pod 'Firebase/AdMob'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
//pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
  # Pods for CloudCar App

  target 'CloudCar AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
